# docker-compose.yml
version: "3"
services:
  app:
    env_file: .env
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    env_file: .env
    image: postgres:alpine
    ports:
      - "35432:5432"